#!/bin/sh
#https://gitlab.com/morgaux/bin

EXIT_STATUS=0
PARENT="$( \
	basename $( \
		cat /proc/$PPID/cmdline 2>/dev/null \
	)\
)"

[ "$#" -gt 0 ] && for CMD in "$@"
do
	[ -x "$(command -v $CMD)" ] && continue
	err "$PARENT missing dependency:'$CMD'"
	EXIT_STATUS=1
done

exit "$EXIT_STATUS"

