#!/bin/sh
#http://gitlab.com/morgaux/bin

#
# slmenu based man searcher
#

[ -x "$(command -v slmenu)" ] || err "slmenu not installed" || exit 1

SEARCH="."

[ "$#" -gt 0 ] && SEARCH="$@"

log "Searching for $SEARCH man page..."

MAN_PAGE="$(man -k "$SEARCH" | awk '{print $1}' | slmenu -i -l 5 -p 'dman:')"

log "$MAN_PAGE man page selected"

man "$MAN_PAGE"

