#!/bin/sh
#http://gitlab.com/morgaux/bin

#
# dmenu based man page searcher
#

for dependancy in dmenu st
do
	if [ -x "$(command -v "$dependancy")" ]
	then
		continue
	fi

	echo "$(basename "$0"): error: $dependancy is not installed." 1>&2
	exit 1
done

st -e man "$( \
	man -k "$( \
		echo "" | dmenu -p 'dman search:' "$@" \
	)" | \
	awk '{print $1}' | \
	dmenu -i -p 'dman page:' "$@" \
)"

