#!/bin/sh
#http://gitlab.com/morgaux/bin

#
# slmenu based man page searcher
#

[ -x "$(command -v slmenu)" ] || exit 1
[ "$#" -gt 0 ] && SEARCH="$*" || SEARCH="."

man "$(man -k "$SEARCH" | awk '{print $1}' | slmenu -i -l 15 -p 'dman:')"

