#!/bin/sh
#http://gitlab.com/morgaux/bin

#
# dmenu / slmenu based command launcher
#

if hasX; then
	# Choose menu util
	MENU="$(command -v dmenu)"

	# Choose term util
	RUNNER="$(command -v st)"
	ARGS="-e"
else
	# Choose menu util
	MENU="$(command -v slmenu)"

	# Choose term util
	RUNNER="/bin/sh"
	ARGS="-c"
fi

[ -x "$MENU" ] && [ -x "$RUNNER" ] || exit 1

$RUNNER "$ARGS" "$(echo "$*" | tr " "  "\n" | "$MENU" -p 'Enter a command: ')"

