#!/bin/sh
# shellcheck disable=SC2068,SC2116

#
# dmenu based dropdown terminal
#

set -e

dependencies dmenu

# Environment setup
[ -n "$DTERM"     ] || export DTERM="dterm"
[ -n "$DHOME"     ] || export DHOME="${HOME}/.dterm/"
[ -n "$DCONFFILE" ] || export DCONFFILE="${HOME}/.dtermrc"
[ -n "$DHISTFILE" ] || export DHISTFILE="${DHOME}/history.dterm"
[ -n "$DHISTSIZE" ] || export DHISTSIZE="500"
[ -d "$DHOME"     ] || mkdir -p "$DHOME"
[ -f "$DCONFFILE" ] || touch "$DCONFFILE"
[ -f "$DHISTFILE" ] || touch "$DHISTFILE"

# Configuration
[ -n "$DSCROLL"   ] || DSCROLL="50"
[ -n "$DPROMPT"   ] || DPROMPT="$(echo "${PWD} \$" | sed -e "s/""$(echo "$HOME" | sed -e 's/\//\\\//g')""/~/g")"

# Main

# truncate history
tail -n "${DHISTSIZE}" "${DHISTFILE}" > "${DHISTFILE}.tmp"

# reverse history through pipe
reverse < "${DHISTFILE}.tmp" | \

	# remove duplicates
	uniq -iu | \

	# pipe through dmenu
	dmenu -l "${DSCROLL}" -p "${DPROMPT}" "$@" | \

	# put selection in the history file
	tee -a "${DHISTFILE}" | \

	# run selection through the shell
	"${SHELL:-"/bin/sh"}" && \

	# and delete temporary history file on completion
	rm "${DHISTFILE}.tmp" & # all in the background

