#!/bin/sh

#
# dmenu based dropdown terminal
#

[ -x "$(command -v dmenu)" ] || exit 1

# Environment setup

[ -n "$DTERM"     ] || export DTERM="dterm"
[ -n "$DHOME"     ] || export DHOME="${HOME}/.dterm/"
[ -n "$DCONFFILE" ] || export DCONFFILE="${HOME}/.dtermrc"
[ -n "$DHISTFILE" ] || export DHISTFILE="${DHOME}/history.dterm"
[ -n "$DHISTSIZE" ] || export DHISTSIZE="50"

[ -d "$DHOME"     ] || mkdir -p "$DHOME"
[ -f "$DCONFILE"  ] || touch "$DCONFFILE"
[ -f "$DHISTILE"  ] || touch "$DHISTFILE"


# Configuration

[ -n "$DSCROLL"   ] || DSCROLL="10"
[ -n "$DPROMPT"   ] || DPROMPT="$(echo "${PWD/$HOME/'~'}") \$"

# Main

# truncate history
TMP_HIST="$(tail -n "$DHISTSIZE" "$DHISTFILE")"
echo "$TMP_HIST" > "$DHISTFILE"

# run dmenu and cmd into shell
tail -n "$DSCROLL" "$DHISTFILE" | \
	awk '{a[i++]=$0} END {for (j=i-1; j>=0;) print a[j--] }' | \
	dmenu -l "${DSCROLL}" -p "${DPROMPT}" "$@" | \
	tee -a "$DHISTFILE" | \
	"${SHELL:-"/bin/sh"}" &

