#!/bin/sh


#
# duso - pronounced "do so", a dmenu sudo frontend
#
# Dynamic
# User
# Substitution
# Oracle
#

FLAGS=""

while [ "$#" -gt 0 ]
do
	case "$1" in
		-*) # looks like an argument
			FLAGS="${FLAGS} ${1}" ;;
		*)  # looks like a command
			break ;;
	esac
	shift
done

echo '' | dmenu -p "[duso] password for ${USER}:" | sudo -S "$@"

