#!/bin/sh

#
# duso - pronounced "do so", a dmenu sudo frontend
#
# Dynamic
# User
# Substitution
# Order
#

set -e

dependencies dmenu sudo

DFLAGS=""

if dmenu -P -v >/dev/null 2>&1 # if password patch installed
then
	DFLAGS="${DFLAGS} -P" # password mode
fi

while [ "$#" -gt 0 ]
do
	case "$1" in
	'-b'|'-f'|'-i'|'-v')
		DFLAGS="$DFLAGS $1" ;;
	'-l'|'-m'|'-p'|'-fn'|'-nb'|'-nf'|'-sb'|'-sf'|'-w')
		DFLAGS="$DFLAGS $1 $2" ; shift ;;
	*)
		break ;;
	esac
	shift
done

# shellcheck disable=SC2086
echo '' | dmenu ${DFLAGS} -p "[duso] password for ${USER}:" | sudo -S "$@"

