#!/bin/sh
# shellcheck disable=SC2068

#
# dmenu based browser searcher / launcher
#

for dependancy in dmenu surf
do
	if [ -x "$(command -v "$dependancy")" ]
	then
		continue
	fi

	echo "$(basename "$0"): error: $dependancy is not installed." 1>&2
	exit 1
done

SELF="$(basename "$0")"
HISTFILE="${HOME}/.${SELF}.hist"

FLAGS=""

while [ "$#" -gt 0 ]
do
	case "$1" in
		'-v'|'-b'|'-f'|'-i')
			# dmenu flag
			FLAGS="${FLAGS} $1"
			;;
		'-l'|'-m'|'-p'|'-fn'|'-nb'|'-nf'|'-sb'|'-sf'|'-w')
			# dmenu flag with second option
			FLAGS="${FLAGS} $1"
			FLAGS="${FLAGS} $2"
			;;
		*)
			# unrecognised option
			break
			;;
	esac
	shift
done

case "$SELF" in
	"dyt")
		URL="https://www.youtube.com/results?search_query=";;
	*)
		URL="http://duckduckgo.com/?q=";;
esac

touch "$HISTFILE"

if [ -z "$@" ]
then
	SEARCH="$(dmenu -p "${SELF}:" ${FLAGS} < "$HISTFILE")"
else
	SEARCH="$@"
fi

surf "${URL}$(echo "$SEARCH" | tee -a "$HISTFILE" | sed 's/ /%20/g')"

