#!/bin/sh
# shellcheck disable=SC2068

#
# dmenu based browser searcher / launcher
#

[ -x "$(command -v dmenu)" ] || exit 1

HIST="$(cat "$HOME/.dweb.hist")"

${BROWSER:-"$(command -v firefox)"} "http://duckduckgo.com/?q=$(echo "$HIST" | dmenu -p "Web Search:" $@ | sed 's/ /%20/g' | tee -a "$HOME/.dweb.hist")"

