#!/bin/sh
# https://gitlab.com/morgaux/etc

##
# dwm wrapper to launch dwm and set the status etc.
##

#symlink to /usr/local/bin/dwm-start:
#ln -sf ~/bin/dwm-start /usr/local/bin/dwm-start

#black bg
xsetroot -solid black

/home/morgaux/bin/dstatus &

sleep 1

# networking
[ -x /usr/bin/nm-applet ] && /usr/bin/nm-applet &

# compositor / transparency
[ -x "$(command -v compton)" ] && compton -b -c

# set wallpaper
[ -x "$(command -v feh)" ] && {
	feh -z -Z --bg-scale /home/morgaux/var/Pictures/Wallpapers/Boy4aow.png
}

[ -x "$(command -v dwm)" ] && {
	exec /usr/local/bin/dwm > /home/morgaux/tmp/dwm.log 2>&1
}

