#!/bin/sh
# https://gitlab.com/morgaux/etc

##
# dwm wrapper to launch dwm and set the status etc.
##

#symlink to /usr/local/bin/dwm-start:
#ln -sf ~/bin/dwm-start /usr/local/bin/dwm-start

#black bg
xsetroot -solid black

/home/morgaux/bin/dstatus &

sleep 1

# networking
/usr/bin/nm-applet &

# transparency
compton -b

# set wallpaper
feh -z -Z --bg-scale /home/morgaux/var/Pictures/Wallpapers/Boy4aow.png

exec /usr/local/bin/dwm > /dev/null

