#!/bin/sh
# shellcheck disable=SC2068

# dmenu youtube search

HIST="$(cat "$HOME/.dyt.hist")"

${BROWSER:-"$(command -v firefox)"} "https://www.youtube.com/results?search_query=$(echo "$HIST" | dmenu -p "YouTube: " $@ | sed 's/ /\%20/g' | tee -a "$HOME/.dyt.hist")"

