#!/bin/sh
#http://gitlab.com/morgaux/bin

#
# print message to stderr
#

[ $# -gt 0 ] && ERRMSG="$@" || ERRMSG="generic error"
PARENT="$(ps -o comm= $PPID)"

echo "$PARENT: $ERRMSG" 1>&2
log "$(ps hf -opid,cmd -C "$$" | awk '$2 !~ /^[|\\]/ { print $1 }' | xargs -L 1 ps -o comm= | awk '{printf "%s"" > ",$0}' | sed 's/ > err > xargs > awk > sed > ps >//g'): $ERRMSG"

exit 1

