#!/bin/sh
#http://gitlab.com/morgaux/bin

#
# print message to stderr
#

ERRMSG="${*}. $(excuse)"
PARENT="$(ps -o comm= $PPID)"

echo "${PARENT}: ${ERRMSG}" 1>&2

log "Error in ${PARENT}: ${ERRMSG}"

exit 1

