#!/bin/sh

#
# git workflow functions
#

git_check()
{
[ -x "$(command -v git)" ] || err "$0: git not found, plase install" || return 1
[ -d "./.git" ] || err "$0: not in a git repo dir" || return 1
}

git_edit()
{
git_check || return 1

e "$@"
git add "$@"
git commit -m "Updated $@ $(date +%F)"
}

git_push()
{
git_check || return 1

for i in 2 1 0; do
	git push && break
	echo "trying again $i more times"
done
}

