#!/bin/sh

##
# sync local git repo
##

SELF="$(basename "$0")"
PIDFILE="$HOME/var/${SELF}.pid"
CURENT_DIR="$PWD"
PATH="$HOME/bin:$PATH"

log "$SELF using $PIDFILE as PID file"

if [ -f "$PIDFILE" ] ; then
	log "PID file found: $(cat "$PIDFILE")"
	log "checking running proccesses..."
	ps -p "$(cat "$PIDFILE")" >/dev/null 2>&1 && { err "Process already running" || exit 1; }
	log "no proccess found, removing PID file."
	rm "$PIDFILE"
fi

log "creating PID file"
echo "$$" > "$PIDFILE" || err "Could not create PID file" || exit 1

##
#
# Begin daemonizable code
#
##

log "checking dependencies..."
[ -x "$(command -v git)" ] || err "git is not installed" || exit 1

usage() {
	echo "$SELF - sync your git repos"
	echo ""
	echo "usage:"
	echo "	$SELF [OPTIONS] PATH ..."
	echo ""
	echo "PATH:"
	echo "	A vaild path to a valid git repository. One or more may"
	echo "	be given separated by spaces. Paths are assumed to be"
	echo "	relavite to './' but may be given as absolute, '/' for"
	echo "	root and '~/' for \$HOME"
	echo ""
	echo "OPTIONS:"
	echo "	NONE YET"
	echo ""
	exit 0
}

[ "$#" -gt 0 ] || usage

while [ "$#" -gt 0 ] ; do
	cd "$CURENT_DIR" || exit 2

	case "$1" in
		"~"*)	REPO="$(echo "$1")";; # expand ~/
		"/"*)	REPO="$1";;
		*)	REPO="$1";;
	esac
	shift

	[ -d "$REPO/.git" ] || err "$REPO is not a valid repository" || continue
	log "entering $REPO..."
	cd "$REPO" || cd "$CURENT_DIR" || exit 2
	URL="$(git config --get remote.origin.url)"
	REMOTE="$(git ls-remote "$URL" HEAD | awk '{print $1}')"
	LOCAL="$(git rev-parse HEAD)"
	[ "$REMOTE" = "$LOCAL" ] && log "remote head and local match" && continue
	git pull || err "could not complete pull"
	cd "$CURENT_DIR" || exit 1
	log "exiting $REPO..."
done

##
#
# End daemonizable code
#
##

log "done, removing PID file"
rm "$PIDFILE" || err "could not remove PID file" || exit 1

exit 0

