#!/bin/sh

#
# http://gitlab.com/morgaux/bin
#

# shell based IDE

# CONSEPT
# combine ~/bin scripts to for together as an IDE

# FEATURES
# edit sourcefiles - use ~/bin/e
# git workflow steps - use ~/bin/gitflow functions
# build system - to be implemented
#	detect syntax
#	detect shebang line
#	decect makefiles
#	run commands based on setup

