#!/bin/sh
#http://gitlab.com/morgaux/bin

#
# log a message to ~/var/log
#

# STAMP format is two numbers, the date and the number of seconds elapsed that day
STAMP="$(date +%y%m%d)-$(echo `expr $(date +%s) % 86400`)"
PARENT="$(ps -o comm= $PPID)"

log_mesg() {
	MSG="$@"
	[ -d "$HOME/var" ] || mkdir -p "$HOME/var"
	[ ! "$MSG" = "" ] && echo "$STAMP : $PARENT : $MSG" >> ~/var/log
}

show_log() {
	tail -n $1 ~/var/log 2>/dev/null && return 0
	tail ~/var/log 2>/dev/null && return 0
	err "log cannot be viewed"
	exit 1
}

trim_log() {
	log "Cutting logfile..."
	tail -n 498 ~/var/log 2>/dev/null 1>~/var/.log.tmp && log "tmp log created" || exit 1
	rm ~/var/log || exit 1
	mv ~/var/.log.tmp ~/var/log && log "logfile restored" || exit 1
	log "Logfile cut"
}

usage() {
	echo "log - log a message to ~/var/log"
	echo "usage: log [ -h | --help ] [ --show ] [ MSG ]"
	echo "options:"
	echo "	-h	--help		show this message"
	echo "	--show			show the last 10 logs"
	echo "	--show LINES		show the last LINES logs"
	echo "	--cut			cut log file 500 lines"
	exit 0
}

[ "$#" -gt 0 ] || exit 0

while true; do
	case $1 in
		-*) case $1 in
			"--show")	show_log; shift;;
			"-h"|"--help")	usage;;
			"--cut")	trim_log; shift;;
			*)	err "unknown option: $1" || exit 1;;
		esac;;
		*) break;;
	esac
done

log_mesg "$@"

