#!/bin/sh
#http://gitlab.com/morgaux/bin

#
# log a message to ~/var/log
#

STAMP="$(date +%c)"
PARENT="$(ps -o comm= $PPID)"

log_mesg() {
	MSG="$*"
	[ -d "$HOME/var" ] || mkdir -p "$HOME/var"
	[ ! "$MSG" = "" ] && echo "$STAMP : $PARENT : $MSG" >> ~/var/log
}

show_log() {
	tail -n "$1" ~/var/log 2>/dev/null && return 0
	tail -n 10 ~/var/log 2>/dev/null && return 1
	err "log cannot be viewed"
	exit 1
}

trim_log() {
	log "cutting logfile..."
	tail -n 498 ~/var/log 2>/dev/null 1>~/var/.log.tmp && log "tmp log created" || exit 1
	rm ~/var/log || exit 1
	mv ~/var/.log.tmp ~/var/log && log "logfile restored" || exit 1
	log "logfile cut"
}

flush_log() {
	rm ~/var/log || err "Could not flush logfile" || exit 1
	log_mesg "Log file flushed."
}

page_log() {
	[ ! -z "$PAGER" ] || err "No PAGER found" || exit 1

	if [ ! -z "$1" ] ; then
		tail -n "$1" ~/var/log 2>/dev/null | "$PAGER"
		return 0
	else
		"$PAGER" ~/var/log
		return 1
	fi
}

usage() {
	echo "log - log a message to ~/var/log"
	echo "usage: log [ -h | --help ] [ --show ] [ MSG ]"
	echo "options:"
	echo "	-h	--help		show this message"
	echo "	--show			show the last 10 logs"
	echo "	--show LINES		show the last LINES of logs"
	echo "	--page			show log in PAGER"
	echo "	--page LINES		show last LINES of logs in PAGER"
	echo "	--cut			cut log file 500 lines"
	echo "	--flush			clear all lines from file"
	exit 0
}

[ "$#" -gt 0 ] || exit 0

while true; do
	case $1 in
		-*) case $1 in
			"--show")	show_log "$2" && shift;		shift;;
			"-h"|"--help")	usage;				shift;;
			"--cut")	trim_log;			shift;;
			"--flush")	flush_log;			shift;;
			"--page")	page_log "$2" && shift;		shift;;
			*)		err "unknown option: $1" || exit 1;;
		esac;;
		*) break;;
	esac
done

log_mesg "$@"

