#!/bin/sh
# http://gitlab.com/morgaux/bin

#
# launch minecraft
#

MINECRAFT_JAR="$HOME/.minecraft/launcher.jar"

[ -x "$(command -v java)" ]     && \
	[ -f "$MINECRAFT_JAR" ] && \
	java -jar "$MINECRAFT_JAR"

