#!/bin/sh

#  WIP shortcut to network selector
# TODO:
# make portabe by directly allowing WiFi networks to be selected and logged into

dependencies nm-connection-editor || exit 1

nm-connection-editor

