#!/bin/sh
#https://gitlab.com/morgaux/bin

#
# Launch popcorn time
#

POP_PATH="$HOME/tmp/Popcorn-Time-0.3.10-Linux-64"
POP_EXEC="Popcorn-Time"

[ -d "$POP_PATH" ] && [ -f "${POP_PATH}/${POP_EXEC}" ] && \
	exec "${POP_PATH}/${POP_EXEC}"

