#!/bin/sh

# Declarations
DOCPATH="$HOME/Documents/SCP"
SELF="$(basename "$0")"

# Functions

# Utils
err() { echo "${SELF}: error: $@" 1>&2 ; }
die() { err "FATAL ERROR: $@" ; exit 1 ; }

# Usage
usage() {
	echo "	SCP - Fetch Secure Contain Protect Foundation Documents"
	echo "	usage: SCP [ OPTIONS ... ] DOCUMENT"
	echo "	options:"
	echo "		-h	--help	show this message"

	exit 0
}

fetchDocument() {
	# download formatted document and cut pre and post
	[ -x "$(command -v w3m)" ] || die "w3m is not installed"
	w3m -dump "http://scp-wiki.wikidot.com/scp-$1"
}

getDocumentSCP() {
	fetchDocument "$1"
}

readDocumentSCP() {
	espeak -f "scp-$1" -w "scp-$1.wav"
}

showDocumentSCP() {
	#[ -d "$DOCPATH" ] || mkdir -p "$DOCPATH"

	case "$1" in
		"all"|"ALL")
			for ID in $(getAllDocumentIds)
			do
				getDocumentSCP "$ID"
			done
			;;
		*)
			getDocumentSCP "$1"
			;;
	esac
}

getAllDocumentIds() {
	# 0 padded to 3 digits
	for l in "" 1 2 3 4 5 6 7 8 9
	do
		for k in 0 1 2 3 4 5 6 7 8 9
		do
			for j in 0 1 2 3 4 5 6 7 8 9
			do
				for i in 0 1 2 3 4 5 6 7 8 9
				do
					echo "$l$k$j$i"
				done
			done
		done | tail -n +2
	done
}

main() {
	[ "$#" -gt 0 ] || usage

	while [ "$#" -gt 0 ]
	do
		case "$1" in
			-h|--help)
				usage
				;;
			*)
				showDocumentSCP "$1"
				;;
		esac
		shift
	done
}

main $@

