#!/bin/sh

# Usage check
usage()
{
	echo "SCP - Fetch Secure Contain Protect Foundation Documents"
	echo "Not to be confused with scp - Secure Copy Protocol"
	echo "usage: SCP [ OPTIONS ... ] DOCUMENT"
	exit 0
}

[ $# -gt 0 ] || usage

# Declarations
DOCPATH="$HOME/Documents/SCP"
LESSDOC="FALSE"
SAVEDOC="FALSE"

# Functions
fetchDocument()
{
	lynx -dump "http://scp-wiki.wikidot.com/scp-$1" | sed -n '/IFRAME/,$p' | tail -n +4 | sed -n '/page revision/q;p'
}

getDocumentSCP()
{
	fetchDocument $1
}

showDocumentSCP()
{
	#[ -d "$DOCPATH" ] || mkdir -p "$DOCPATH"

	case "$1" in
		"all"|"ALL")
			for ID in $(getAllDocumentIds); do
				getDocumentSCP $ID
			done
			;;
		*)
			getDocumentSCP $1
			;;
	esac
}

getAllDocumentIds()
{
	for l in "" 1 2 3 4 5 6 7 8 9; do
		for k in 0 1 2 3 4 5 6 7 8 9; do
			for j in 0 1 2 3 4 5 6 7 8 9; do
				for i in 0 1 2 3 4 5 6 7 8 9; do
					echo "$l$k$j$i"
				done
			done
		done | tail -n+2
	done
}

main()
{
	while [ $# -gt 0 ] ; do
		case $1 in
			-h|--help)
				shift
				usage
				;;
			-l|--less)
				shift
				LESSDOC="TRUE"
				;;
			-s|--save)
				shift
				SAVEDOC="TRUE"
				;;
			*)
				showDocumentSCP "$1"
				shift
				;;
		esac
	done
}

main "$@"

