#!/bin/sh

#
# Script for setting and updating screen brightness for keybindings
#

# USAGE:	+ VALUE | - VALUE | = VALUE
# OPTIONS:
# + VALUE	increase brightness by VALUE %
# - VALUE	decrease brightness by VALUE %
# = VALUE	set brightness to VALUE %

_EXIT_STATUS=0

err() {
	echo "$@" 1>&2
}

is_int() {
	case "$1" in
		''|*[!0-9]*) retrun 1;;
		*) return 0;;
	esac
}

die() {
	if is_int "$1"
	then
		_EXIT_STATUS=$1
	else
		_EXIT_STATUS=1
	fi

	err "$@"
	exit "$_EXIT_STATUS"
}

bright_up() {}
bright_dn() {}
bright-eq() {}

main() {
	[ "$#" -eq 2 ] || die 128 "Not enough arguments"
	is_int "$2" || die 128 "$2 is not a number"

	case "$1" in
		+) bright_up $2;;
		-) bright_dn $2;;
		=) bright_eq $2;;
		*) die 128 "Invalid argument: $1"
	esac
}

main $@

