#!/bin/sh

#
# Script for setting and updating volume for keybindings
#

# USAGE:	+ VALUE | - VALUE | = VALUE
# OPTIONS:
# + VALUE	increase volume by VALUE %
# - VALUE	decrease volume by VALUE %
# = VALUE	set volume to VALUE %

_EXIT_STATUS=0

err() {
	echo "$@" 1>&2
}

is_int() {
	case "$1" in
		''|*[!0-9]*) retrun 1;;
		*) return 0;;
	esac
}

die() {
	if is_int "$1"
	then
		_EXIT_STATUS=$1
		shift
	else
		_EXIT_STATUS=1
	fi

	err "$@"
	exit "$_EXIT_STATUS"
}

add() { # TODO
	echo "$1 + $2"
}

sub() { # TODO
	echo "$1 - $2"
}

vol_up() {
	NEW_PERCENT="$(add "$CURRENT" "$1")"

	if [ "$NEW_PERCENT" -gt 100 ]
	then
		return 0
	fi

	vol_eq "$NEW_PERCENT"
}

vol_dn() {
	NEW_PERCENT="$(sub "$CURRENT" "$1")"

	if [ "$NEW_PERCENT" -lt 0 ]
	then
		return 0
	fi

	vol_eq "$NEW_PERCENT"
}

vol_eq() { # TODO
	return 0
}

main() {
	[ "$#" -eq 2 ] || die 128 "Not enough arguments"
	is_int "$2" || die 128 "$2 is not a number"

	case "$1" in
		+) vol_up "$2" ;;
		-) vol_dn "$2" ;;
		=) vol_eq "$2" ;;
		*) die 128 "Invalid argument: $1"
	esac

	return "$_EXIT_STATUS"
}

main "$@"

