#!/bin/sh

#
# open a tabbed st instance
#

hasX || exit 1

[ -x "$(command -v st)" ] || err "suckless terminal not found" || exit 1
[ -x "$(command -v tabbed)" ] || err "tabbed not found" || exit 1

tabbed -c -k -r 2 st -w '' -t 'tabbed terminal' "$@"

