#!/bin/sh
#http://gitlab.com/morgaux/bin

#
# Execute apropriate ufetch, depends on ufetch-* in ~/src/ufetch
#

UFDIR="$HOME/src/ufetch"

for UF in $(echo "${UFDIR}/ufetch-"* | tr ' -' '\n ' | grep -v png | awk '{print $2}')
do
	if grep -q -i "$UF" /etc/*release* >/dev/null 2>&1
	then
		"ufetch-$UF" 2>/dev/null
		exit $?
	fi

	if uname -a | grep -q -i "$UF"
	then
		"ufetch-$UF" 2>/dev/null
		exit $?
	fi
done

err "no ufetch selected"
exit 1

