#!/bin/sh
#http://gitlab.com/morgaux/bin

#
# Execute apropriate ufetch, depends on ufetch-* in ~/src/ufetch
#

UFDIR="$HOME/src/ufetch"
UFREPO="https://gitlab.com/jschx/ufetch"
OSDETAILS="$(cat /etc/*release*)"
OSLIST=""

mkdir -p "$(dirname $UFDIR)"

if [ ! -d "$UFDIR" ]
then
	[ -x "$(command -v git)" ] || {
		err "ufetch could not be installed, please install git first"
		exit 1
	}

	log "ufetch not installed, cloning $UFREPO"
	log "$(git clone "$UFREPO" "$UFDIR" 2>&1)"
fi

os_list() {
	echo "$(\
			for OS in \
				$(echo "${UFDIR}/ufetch-"* | \
					tr ' -' '\n ' | \
					grep -v png | \
					awk '{print $2}'); \
			do \
				if echo "$OSDETAILS" | grep -q -i "$OS"; \
				then \
					echo "$(echo "$OSDETAILS" | \
						tr ' ' '\n' | \
						grep -i $OS | \
						wc -l):$OS"; \
				fi \
			done\
		)"
}

[ -n "$(os_list)" ] || {
	OSDETAILS="$(uname -a | cat - /etc/*release*)"
}

[ -n "$(os_list)" ] || {
	err "no ufetch selected"
	exit 1
}

exec "${UFDIR}/ufetch-$(echo "$(os_list)" | \
	sort -r -n | \
	head -1 | \
	tr ':' ' ' | \
	awk '{print $2}')"

